// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Savico.Infrastructure;

#nullable disable

namespace Savico.Infrastructure.Migrations
{
    [DbContext(typeof(SavicoDbContext))]
    [Migration("20241204114028_SeedAdminDb")]
    partial class SeedAdminDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9365c92c-dcb7-4c90-aa4c-c3460905eea0",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "f2aaa3b1-3cd0-4384-b843-0c022bbfcf63",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("IdentityUserRole<Guid>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6",
                            RoleId = "9365c92c-dcb7-4c90-aa4c-c3460905eea0"
                        },
                        new
                        {
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1",
                            RoleId = "f2aaa3b1-3cd0-4384-b843-0c022bbfcf63"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Savico.Core.Models.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Budget identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("Budget's end date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the budget is soft-deleted");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Budget's start date");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Budget's total amount");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Budgets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 1000000.00m,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 1000000.00m,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        });
                });

            modelBuilder.Entity("Savico.Core.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Expense identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Expense's amount");

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Date of expense");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasComment("Expense's description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the expense is soft-deleted");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100m,
                            BudgetId = 1,
                            CategoryId = 1,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electricity bill",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 150m,
                            BudgetId = 1,
                            CategoryId = 3,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supermarket shopping",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 5m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amazon Prime monthly subscription",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 10m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Netflix monthly subscription",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 13m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "World of Warcraft monthly subscription",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 6,
                            Amount = 100m,
                            BudgetId = 1,
                            CategoryId = 11,
                            Date = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 7,
                            Amount = 35m,
                            BudgetId = 1,
                            CategoryId = 13,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bought a new pair of jeans",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 8,
                            Amount = 50m,
                            BudgetId = 1,
                            CategoryId = 12,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Donated to a local animal shelter",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 9,
                            Amount = 40m,
                            BudgetId = 1,
                            CategoryId = 4,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bought a new video game from Steam",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 10,
                            Amount = 50m,
                            BudgetId = 1,
                            CategoryId = 9,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Went to check my teeth",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 11,
                            Amount = 30m,
                            BudgetId = 1,
                            CategoryId = 1,
                            Date = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Water bill",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 12,
                            Amount = 100m,
                            BudgetId = 1,
                            CategoryId = 13,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bought a new pair of sneakers",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 13,
                            Amount = 17m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Disney+ monthly subscription",
                            IsDeleted = false,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 14,
                            Amount = 80m,
                            BudgetId = 1,
                            CategoryId = 1,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Electricity bill",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 15,
                            Amount = 100m,
                            BudgetId = 1,
                            CategoryId = 3,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Supermarket shopping",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 16,
                            Amount = 5m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Amazon Prime monthly subscription",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 17,
                            Amount = 10m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Netflix monthly subscription",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 18,
                            Amount = 13m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "World of Warcraft monthly subscription",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 19,
                            Amount = 70m,
                            BudgetId = 1,
                            CategoryId = 11,
                            Date = new DateTime(2024, 12, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 20,
                            Amount = 35m,
                            BudgetId = 1,
                            CategoryId = 13,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bought a new pair of jeans",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 21,
                            Amount = 50m,
                            BudgetId = 1,
                            CategoryId = 12,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Donated to a local animal shelter",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 22,
                            Amount = 40m,
                            BudgetId = 1,
                            CategoryId = 4,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bought a new video game from Steam",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 23,
                            Amount = 50m,
                            BudgetId = 1,
                            CategoryId = 9,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Went to check my teeth",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 24,
                            Amount = 30m,
                            BudgetId = 1,
                            CategoryId = 1,
                            Date = new DateTime(2024, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Water bill",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 25,
                            Amount = 90m,
                            BudgetId = 1,
                            CategoryId = 13,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bought a new pair of sneakers",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 26,
                            Amount = 27m,
                            BudgetId = 1,
                            CategoryId = 10,
                            Date = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Disney+ monthly subscription",
                            IsDeleted = false,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        });
                });

            modelBuilder.Entity("Savico.Core.Models.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Goal identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ContributionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Contribution towards the set goal");

                    b.Property<decimal>("CurrentAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("User's current amount towards goal");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Goal description");

                    b.Property<bool>("IsAchieved")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the goal is achieved or not");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the goal is soft-deleted");

                    b.Property<DateTime?>("LastContributionDate")
                        .HasColumnType("datetime2")
                        .HasComment("Last date that a contribution was made on");

                    b.Property<decimal>("TargetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Goal's target amount");

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2")
                        .HasComment("Target date for reaching the goal");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Goals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContributionAmount = 0m,
                            CurrentAmount = 0m,
                            Description = "Saving for my trip to Denmark",
                            IsAchieved = false,
                            IsDeleted = false,
                            TargetAmount = 1500m,
                            TargetDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 2,
                            ContributionAmount = 0m,
                            CurrentAmount = 0m,
                            Description = "Saving for my PC upgrade",
                            IsAchieved = false,
                            IsDeleted = false,
                            TargetAmount = 500m,
                            TargetDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 3,
                            ContributionAmount = 0m,
                            CurrentAmount = 0m,
                            Description = "Saving for my trip to Denmark",
                            IsAchieved = false,
                            IsDeleted = false,
                            TargetAmount = 1500m,
                            TargetDate = new DateTime(2025, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 4,
                            ContributionAmount = 0m,
                            CurrentAmount = 0m,
                            Description = "Saving for my PC upgrade",
                            IsAchieved = false,
                            IsDeleted = false,
                            TargetAmount = 500m,
                            TargetDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        });
                });

            modelBuilder.Entity("Savico.Core.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Income identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Income's amount");

                    b.Property<int?>("BudgetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasComment("Date of receiving the income");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the income is soft-deleted");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Income's source");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("UserId");

                    b.ToTable("Incomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2700m,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Source = "Salary",
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 200m,
                            Date = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Source = "Freelance",
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 100m,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Source = "Investments",
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 2350m,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Source = "Salary",
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 150m,
                            Date = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            Source = "Freelance",
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        });
                });

            modelBuilder.Entity("Savico.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("BudgetId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("User's currency");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("User's first name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the user is soft-deleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("User's last name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad5a5ccb-2be1-4866-b151-0f09a58416f6",
                            AccessFailedCount = 0,
                            BudgetId = 1,
                            ConcurrencyStamp = "b4a07b8e-fc4a-4b3b-9a48-1331363e19c6",
                            Currency = "EUR",
                            Email = "testuser123@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Test",
                            IsDeleted = false,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "TESTUSER123@GMAIL.COM",
                            NormalizedUserName = "TESTUSER123@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFUCjmMrfspY8lSBatM2CVpoFXkgfg9wmw6vKRRWTqiImUKWFm+l8G+k+JDAAJ4kUQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0302f72c-0a75-46b9-80fa-86c8058a9a47",
                            TwoFactorEnabled = false,
                            UserName = "testuser123@gmail.com"
                        },
                        new
                        {
                            Id = "7c55600b-d374-4bfb-8352-a65bf7d44cc1",
                            AccessFailedCount = 0,
                            BudgetId = 2,
                            ConcurrencyStamp = "35bb4e58-cc3b-418d-8e6f-7b27594dc913",
                            Currency = "USD",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            FirstName = "TEST",
                            IsDeleted = false,
                            LastName = "ADMIN",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMuEl97P63qfTaa6RbojB4xevE33UHgm7MqUvHBJfkqtKxaYfv0sWVBNz9xrQIz+5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "06cecd91-e57c-43d2-9669-ff7734c5d7c7",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        });
                });

            modelBuilder.Entity("Savico.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExpenseId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rent"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mortgage"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Property taxes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Insurance"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Transportation"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Health"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Subscription"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Bank loan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Donation"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Clothing"
                        });
                });

            modelBuilder.Entity("Savico.Infrastructure.Data.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Report identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasComment("End date of the report period");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasComment("Indicates if the report is soft-deleted");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasComment("Start date of the report period");

                    b.Property<decimal>("TotalExpense")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total expense during the period");

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total income during the period");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasComment("User who created the report");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalExpense = 0m,
                            TotalIncome = 0m,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalExpense = 700m,
                            TotalIncome = 3000m,
                            UserId = "ad5a5ccb-2be1-4866-b151-0f09a58416f6"
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StartDate = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalExpense = 0m,
                            TotalIncome = 0m,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalExpense = 600m,
                            TotalIncome = 2500m,
                            UserId = "7c55600b-d374-4bfb-8352-a65bf7d44cc1"
                        });
                });

            modelBuilder.Entity("Savico.Infrastructure.Data.Models.Tip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Tips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Buy generic bread, save for your dream yacht."
                        },
                        new
                        {
                            Id = 2,
                            Content = "Don't let your spending get out of control—unless it's a coupon you found in your pocket!"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Budgeting is like dieting. You can’t keep eating chips if you want to fit in your financial goals."
                        },
                        new
                        {
                            Id = 4,
                            Content = "Save your change. Someday, it might be worth a lot... or at least enough for a nice coffee."
                        },
                        new
                        {
                            Id = 5,
                            Content = "It’s not ‘expensive coffee,’ it’s ‘investment in happiness’—unless your budget says otherwise."
                        },
                        new
                        {
                            Id = 6,
                            Content = "Don’t stress about your budget—just make sure your credit card doesn’t get any ideas."
                        },
                        new
                        {
                            Id = 7,
                            Content = "Saving money is like washing your car—you feel like you're not getting anywhere, but it’s worth it in the end."
                        },
                        new
                        {
                            Id = 8,
                            Content = "Don’t spend your money too fast—unless it's on ice cream, because ice cream is always worth it."
                        },
                        new
                        {
                            Id = 9,
                            Content = "Financial freedom is just a few small sacrifices away... starting with not buying that extra pair of shoes."
                        },
                        new
                        {
                            Id = 10,
                            Content = "Be patient and persistent in achieving your financial goals."
                        },
                        new
                        {
                            Id = 11,
                            Content = "Always compare prices before making significant purchases."
                        },
                        new
                        {
                            Id = 12,
                            Content = "Save a portion of any raise or bonus you receive."
                        },
                        new
                        {
                            Id = 13,
                            Content = "Start budgeting and keep track of all income and expenses."
                        },
                        new
                        {
                            Id = 14,
                            Content = "Review your budget regularly to stay on track."
                        },
                        new
                        {
                            Id = 15,
                            Content = "Always plan for the future, not just for the present."
                        },
                        new
                        {
                            Id = 16,
                            Content = "Try to build an emergency fund for unexpected expenses."
                        },
                        new
                        {
                            Id = 17,
                            Content = "Set realistic financial goals and work towards them consistently."
                        },
                        new
                        {
                            Id = 18,
                            Content = "Track your spending to know where your money is going."
                        },
                        new
                        {
                            Id = 19,
                            Content = "Put your savings in a jar... and then hide it from yourself so you can’t spend it!"
                        },
                        new
                        {
                            Id = 20,
                            Content = "Save money by spending it on things that’ll last forever, like a good pair of socks (because socks don’t expire)."
                        },
                        new
                        {
                            Id = 21,
                            Content = "If you save enough money, you can one day buy that thing you don’t need. Think of the possibilities!"
                        },
                        new
                        {
                            Id = 22,
                            Content = "You can’t buy happiness, but you can buy a savings account, and that’s pretty much the same thing."
                        },
                        new
                        {
                            Id = 23,
                            Content = "Turn your coffee habit into a savings plan: swap your latte for instant coffee, then use the savings to buy something ridiculous!"
                        },
                        new
                        {
                            Id = 24,
                            Content = "Save on heating bills by wearing all your clothes at once—fashion is subjective, right?"
                        },
                        new
                        {
                            Id = 25,
                            Content = "Instead of spending money on fancy things, spend time with people who think free stuff is cool."
                        },
                        new
                        {
                            Id = 26,
                            Content = "Save on heating bills by wearing all your clothes at once—fashion is subjective, right?"
                        },
                        new
                        {
                            Id = 27,
                            Content = "Cut costs by cutting back on things you don’t really need, like your subscription to the ‘I like pizza’ fan club."
                        },
                        new
                        {
                            Id = 28,
                            Content = "Put your savings in a piggy bank and then give it a name. If you bond with it, you’ll resist the urge to break it open."
                        },
                        new
                        {
                            Id = 29,
                            Content = "The best way to save money? Stop buying things that seem like a good idea at 2 a.m. after too much coffee."
                        },
                        new
                        {
                            Id = 30,
                            Content = "Saving money is like a treasure hunt. The more you save, the more you realize it was worth the effort—and the loot is much cooler than that impulse buy."
                        },
                        new
                        {
                            Id = 31,
                            Content = "To save more, stop buying things you don’t need and start selling things you forgot you bought."
                        },
                        new
                        {
                            Id = 32,
                            Content = "Remember: Money can’t buy happiness, but it can buy a ton of snacks for your movie marathon. And that’s basically the same thing."
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Savico.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Savico.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Savico.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Savico.Core.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Savico.Core.Models.Budget", b =>
                {
                    b.HasOne("Savico.Core.Models.User", "User")
                        .WithOne("Budget")
                        .HasForeignKey("Savico.Core.Models.Budget", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Savico.Core.Models.Expense", b =>
                {
                    b.HasOne("Savico.Core.Models.Budget", "Budget")
                        .WithMany("Expenses")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Savico.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Savico.Core.Models.User", "User")
                        .WithMany("Expenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Budget");

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Savico.Core.Models.Goal", b =>
                {
                    b.HasOne("Savico.Core.Models.User", "User")
                        .WithMany("Goals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Savico.Core.Models.Income", b =>
                {
                    b.HasOne("Savico.Core.Models.Budget", null)
                        .WithMany("Incomes")
                        .HasForeignKey("BudgetId");

                    b.HasOne("Savico.Core.Models.User", "User")
                        .WithMany("Incomes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Savico.Infrastructure.Data.Models.Category", b =>
                {
                    b.HasOne("Savico.Core.Models.Expense", null)
                        .WithMany("Categories")
                        .HasForeignKey("ExpenseId");
                });

            modelBuilder.Entity("Savico.Infrastructure.Data.Models.Report", b =>
                {
                    b.HasOne("Savico.Core.Models.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Savico.Core.Models.Budget", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("Savico.Core.Models.Expense", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Savico.Core.Models.User", b =>
                {
                    b.Navigation("Budget")
                        .IsRequired();

                    b.Navigation("Expenses");

                    b.Navigation("Goals");

                    b.Navigation("Incomes");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("Savico.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
